from .speedmatch_footorient_joint_smooth_reward import *
from .speedmatch_reward import *
from .trajmatch_reward import *
from .speedmatch_heuristic_reward import *
from .side_speedmatch_reward import *
from .side_speedmatch_foottraj_reward import *
from .side_speedmatch_heightvel_reward import *
from .side_speedmatch_heuristic_reward import *
from .side_speedmatch_torquemsooth_reward import *